Document: gnome-shell-extension-lunar-clock
Title: Debian gnome-shell-extension-lunar-clock Manual
Author: <insert document author here>
Abstract: This manual describes what gnome-shell-extension-lunar-clock is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gnome-shell-extension-lunar-clock/gnome-shell-extension-lunar-clock.sgml.gz

Format: postscript
Files: /usr/share/doc/gnome-shell-extension-lunar-clock/gnome-shell-extension-lunar-clock.ps.gz

Format: text
Files: /usr/share/doc/gnome-shell-extension-lunar-clock/gnome-shell-extension-lunar-clock.text.gz

Format: HTML
Index: /usr/share/doc/gnome-shell-extension-lunar-clock/html/index.html
Files: /usr/share/doc/gnome-shell-extension-lunar-clock/html/*.html
